In [2]:
import pandas as pd

In [3]:
ratings = pd.read_csv('averaged_ratings.csv')
raw_scores = pd.read_csv('PerformanceAssessmentData_finish_corrected_filtered.csv', sep=';')

In [9]:
ratings.head()

,Participant Number,Age,Gender,Case_Number,Experience_Total,Position,GRS_Total,OSATS_Total,CFS_Total,Self_Rating
0,1,28,m,1,2.0,Assistenzarzt/Assistenzärztin,59.25,23.0,9.25,3.0
1,1,28,m,2,2.0,Assistenzarzt/Assistenzärztin,54.40,24.6,10.80,4.0
2,1,28,m,3,2.0,Assistenzarzt/Assistenzärztin,74.50,30.0,9.50,4.0
3,2,28,m,1,3.0,Assistenzarzt/Assistenzärztin,49.25,19.5,9.50,1.0
4,2,28,m,2,3.0,Assistenzarzt/Assistenzärztin,49.00,16.5,8.00,1.0

In [10]:
raw_scores.head()

,Zeitstempel,Participant number (XXX),Expert number,1.2 Time and Motion,1.3 Instrument Handling,1.4 Knowledge of Instruments,1.5 Flow of Procedure,1.6 Knowledge of Specific Procedure,1.7 Overall Performance,1.8 Quality of final product,...,3.8 Lag screw perpendicular to fracture/ does not displace fracture,"3.9 If not lag screw, achieves compression with plate",3.10 Safely/ effectively holds plate on bone with forceps/clamp/wire,3.11 Screws drilled using appropriate guide/ soft tissue protector,3.12 Plate appropriately secured to bone in reasonable position,3.13 all screws appropriate length,CFS Overall,Did you recognize the participant?,Participant Number,Case Type
0,2024/05/08 1:01:40 PM OESZ,101,2,9,9,9,9,9,9,9,...,1,,1,1,1,1,12,No,10,radius
1,2024/05/08 1:06:06 PM OESZ,111,2,7,7,7,7,7,7,7,...,1,,1,1,1,1,12,No,11,radius
2,2024/05/08 1:08:16 PM OESZ,121,2,7,7,7,7,7,7,7,...,1,,1,1,1,1,12,No,12,radius
3,2024/05/08 1:14:56 PM OESZ,131,2,5,5,5,5,6,6,6,...,1,,1,1,1,1,11,No,13,radius
4,2024/05/08 1:17:27 PM OESZ,141,2,10,10,10,10,10,10,10,...,1,,1,1,1,1,12,Yes,14,radius

In [6]:
"""
Case_Number <=> Case Type mapping:
1 - radius
2 - malleolus
3 - Ulna
"""
raw_scores['Case_Number'] = raw_scores['Case Type'].map({'radius': 1, 'malleolus': 2, 'Ulna': 3})
avg_raw_scores = raw_scores.groupby(['Participant Number', 'Case_Number'])['QRS Overal'].mean().reset_index()
df_merged = pd.merge(ratings, avg_raw_scores[['QRS Overal', 'Case_Number', 'Participant Number']], on=['Participant Number', 'Case_Number'], how='inner')
# drop rows with missing GRS_Total
df_merged = df_merged.dropna(subset=['QRS Overal'])
df_merged.rename(columns={'QRS Overal': 'QRS_Overal'}, inplace=True)
# save as csv
df_merged.to_csv('merged_scores.csv', index=False)

In [5]:
df_merged

,Participant Number,Age,Gender,Case_Number,Experience_Total,Position,GRS_Total,OSATS_Total,CFS_Total,Self_Rating,QRS_Overal
0,1,28,m,1,2.0,Assistenzarzt/Assistenzärztin,59.25,23.00,9.25,3.0,48.50
1,1,28,m,2,2.0,Assistenzarzt/Assistenzärztin,54.40,24.60,10.80,4.0,45.00
2,1,28,m,3,2.0,Assistenzarzt/Assistenzärztin,74.50,30.00,9.50,4.0,60.50
3,2,28,m,1,3.0,Assistenzarzt/Assistenzärztin,49.25,19.50,9.50,1.0,39.25
4,2,28,m,2,3.0,Assistenzarzt/Assistenzärztin,49.00,16.50,8.00,1.0,38.00
...,...,...,...,...,...,...,...,...,...,...,...
78,28,31,m,2,4.0,Assistenzarzt/Assistenzärztin,72.25,35.25,12.25,5.0,59.75
79,28,31,m,3,4.0,Assistenzarzt/Assistenzärztin,70.00,28.25,9.75,5.0,56.50
80,29,24,w,1,0.0,Unterassistenzarzt/Unterassistenzärztin,49.75,18.00,10.50,4.0,40.75
81,29,24,w,2,0.0,Unterassistenzarzt/Unterassistenzärztin,62.00,32.75,10.50,2.0,50.25
82,29,24,w,3,0.0,Unterassistenzarzt/Unterassistenzärztin,61.25,19.00,9.75,4.0,49.50