## Check that the Window Dataset class works

In [1]:
import os
import pandas as pd
from tqdm import tqdm
if os.getcwd().endswith("notebooks"):
    os.chdir("../")

from src.embeddings.dataset import WindowDataset, WindowDatasetTCN
from src.embeddings.train import train_autoencoder
from torch.utils.data import DataLoader
from src.embeddings.models import MotionAutoencoder, MotionAutoencoderOld

In [2]:
processed_path = "data/processed"
paths = [os.path.join(processed_path, f) for f in os.listdir(processed_path) if f.endswith("10fps_processed.pkl")]

df_dict = {}
cols_to_keep = ['frame', 'hand_label', 'cx_smooth', 'cy_smooth']

# load df with where first column in csv serves as index
df_vid_name_map = pd.read_csv("data/scores/vid_name_map.csv", index_col=0)

with tqdm(total=len(paths), desc="Loading processed data") as pbar:
    for path in paths:
        vid = os.path.basename(path).replace("_10fps_processed.pkl", "")
        vid = vid.replace("hand_tracking_", "")
        participant_id = df_vid_name_map.loc[vid]['Participant Number']
        #if int(participant_id) == 8:
        #    continue
        df_dict[(vid, int(participant_id))] = pd.read_pickle(path)[cols_to_keep]
        pbar.update(1)

Loading processed data: 100%|██████████| 86/86 [00:11<00:00,  7.37it/s]

In [11]:
validation_goups = [1, 11, 17, 18]
train_groups = [g for g in range(1, 30) if (g not in validation_goups or g==8)]

train_df_dict = {key: df_dict[key] for key in df_dict.keys() if key[1] in train_groups}
val_df_dict = {key: df_dict[key] for key in df_dict.keys() if key[1] in validation_goups}

train_dataset = WindowDatasetTCN(
    df_dict=train_df_dict,
    window_size=20,
    step_size=10,
    hand="Right", 
    fps=10,
)

val_dataset = WindowDatasetTCN(
    df_dict=val_df_dict,
    window_size=20,
    step_size=10,
    hand="Right", 
    fps=10,
    scaling_stats=train_dataset.scaling_stats
)

Processing Right Hand Windows: 100%|██████████| 74/74 [00:00<00:00, 126.64it/s]

Computing robust scaling statistics from training data...

Processing Right Hand Windows: 100%|██████████| 12/12 [00:00<00:00, 110.96it/s]

In [4]:
import numpy as np

all_data = np.array([feats for feats, _ in train_dataset] + [feats for feats, _ in val_dataset])

# (N, T, C) -> (N x T, C)
all_data_reshaped = all_data.reshape(-1, all_data.shape[-1])

# turn into dataframe and describe
df_all_data = pd.DataFrame(all_data_reshaped, columns=["dx", "dy", "vx", "vy", "ax", "ay", "mask"])
df_all_data[df_all_data['mask']==1].describe()

,dx,dy,vx,vy,ax,ay,mask
count,690299.000000,690299.000000,690299.000000,690299.000000,690299.000000,690299.000000,690299.0
mean,0.057956,-0.031232,0.057956,-0.031232,-0.031529,-0.004615,1.0
std,1.628733,1.504155,1.628734,1.504156,1.582865,1.488726,0.0
min,-5.000000,-5.000000,-5.000000,-5.000000,-5.000000,-5.000000,1.0
25%,-0.414764,-0.469515,-0.414764,-0.469515,-0.488387,-0.495997,1.0
50%,-0.005668,0.000000,-0.005668,0.000000,0.007734,-0.007994,1.0
75%,0.517047,0.469508,0.517047,0.469508,0.457337,0.456015,1.0
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1.0

Processing videos: 100%|██████████| 86/86 [00:02<00:00, 29.20it/s]

In [23]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False)

In [ ]:
ae = MotionAutoencoder(feature_dim=7, latent_dim=16, dropout_prob=0.1).to("cpu")
best_model, _ = train_autoencoder(ae, train_loader, val_loader=val_loader, epochs=50, lr=0.01)

Epoch 001: 100%|██████████| 952/952 [00:04<00:00, 193.03it/s]

Epoch 001 — train: 12.764852 | val: 242.586416

Epoch 002: 100%|██████████| 952/952 [00:05<00:00, 185.92it/s]

Epoch 002 — train: 11.830241 | val: 229.240870

Epoch 003: 100%|██████████| 952/952 [00:04<00:00, 205.62it/s]

Epoch 003 — train: 11.432525 | val: 226.642804

Epoch 004: 100%|██████████| 952/952 [00:04<00:00, 203.96it/s]

Epoch 004 — train: 11.240224 | val: 220.712968

Epoch 005: 100%|██████████| 952/952 [00:04<00:00, 195.80it/s]

Epoch 005 — train: 10.908575 | val: 215.529580

Epoch 006: 100%|██████████| 952/952 [00:05<00:00, 174.62it/s]

KeyboardInterrupt:

In [ ]:
ae = MotionAutoencoderOld(
        feature_dim=7,
        latent_dim=16,
        dropout_prob=0.1
    ).to("cpu")
best_model, _ = train_ae(train_dataset, feature_dim=7, latent_dim=16, batch_size=32, epochs=50, lr=1e-3, device="cpu")

KeyboardInterrupt:

# Training of the Autoencoder

In [14]:
def train_ae(
    dataset,
    feature_dim=5,              # now includes "valid" channel
    latent_dim=16,
    batch_size=16,
    epochs=50,
    lr=1e-3,
    device="cpu",
    patience=10,
    delta=1e-5,
    lambda_aug=0.0,             # set > 0 to enable augmentation consistency loss
):
    """
    Train MotionAutoencoder with masked loss and optional synthetic gap augmentation.
    Assumes last feature in input is 'valid' mask.
    """
    
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    ae = MotionAutoencoder(
        feature_dim=feature_dim,
        latent_dim=latent_dim,
        dropout_prob=0.1 if lambda_aug > 0 else 0.0
    ).to(device)

    optimizer = torch.optim.Adam(ae.parameters(), lr=lr)

    best_loss = float("inf")
    best_state = None
    wait = 0

    ae.train()
    for epoch in range(epochs):

        epoch_loss = 0.0

        for x, _ in dataloader:

            x = x.to(device)

            motion = x[..., :-1]          # real motion
            valid = x[..., -1:]           # (batch, T, 1)

            optimizer.zero_grad()

            # ------ PASS 1: normal input ------
            out, latent_clean = ae(x)     # recon motion only

            # masked MSE
            diff = (out - motion) * valid
            mse_recon = (diff ** 2).sum() / (valid.sum() + 1e-6)

            # ------ PASS 2: augmented input ------
            if lambda_aug > 0:
                x_aug = x.clone()
                B, T, D = x_aug.shape

                # randomly drop some valid frames (fake tracking loss)
                drop_mask = (torch.rand(B, T, 1, device=device) < 0.1)
                x_aug[..., :-1] = x_aug[..., :-1] * (~drop_mask)   # zero out motion at dropped frames
                # keep valid mask unchanged

                _, latent_aug = ae(x_aug)

                # consistency loss
                mse_aug = torch.mean((latent_clean - latent_aug)**2)
            else:
                mse_aug = 0.0

            total_loss = mse_recon + lambda_aug * mse_aug
            total_loss.backward()
            optimizer.step()

            epoch_loss += total_loss.item() * x.size(0)

        epoch_loss /= len(dataset)
        print(f"Epoch {epoch+1:03d} — loss: {epoch_loss:.6f}")

    if best_state is not None:
        ae.load_state_dict(best_state)

    return ae, best_loss

In [12]:
dataset = WindowDataset(df_dict, hand="Right", feature_mode="pos_vel", window_size=20, step_size=5, orig_fps=30.0, max_gap_seconds=0.11, normalize=True)

train_dataset = WindowDataset(
    df_dict=train_df_dict,
    window_size=20,
    step_size=5,
    hand="Right", 
    orig_fps=30.0, max_gap_seconds=0.11, normalize=True
)

val_dataset = WindowDataset(
    df_dict=val_df_dict,
    window_size=20,
    step_size=5,
    hand="Right", 
    orig_fps=30.0, max_gap_seconds=0.11, normalize=True
)

Processing videos: 100%|██████████| 86/86 [00:02<00:00, 30.35it/s]
Processing videos: 100%|██████████| 74/74 [00:02<00:00, 32.95it/s]
Processing videos: 100%|██████████| 12/12 [00:00<00:00, 30.25it/s]

In [16]:
import numpy as np

all_data = np.array([feats for feats, _ in train_dataset] + [feats for feats, _ in val_dataset])

# (N, T, C) -> (N x T, C)
all_data_reshaped = all_data.reshape(-1, all_data.shape[-1])

# turn into dataframe and describe
df_all_data = pd.DataFrame(all_data_reshaped, columns=["x", "y", "vx", "vy", "mask"])
df_all_data[df_all_data['mask']==1].describe()

                  x             y            vx            vy       mask
count  1.491516e+06  1.491516e+06  1.491516e+06  1.491516e+06  1491516.0
mean   3.923284e-01  3.497153e-01  3.320170e-03 -1.630157e-03        1.0
std    8.891776e-02  1.509243e-01  8.142461e-02  1.032245e-01        0.0
min   -4.970238e-03 -4.753968e-02 -1.846912e+00 -2.990741e+00        1.0
25%    3.404762e-01  2.119312e-01 -9.747148e-03 -1.970917e-02        1.0
50%    3.959375e-01  3.395767e-01  8.185208e-04  7.936358e-04        1.0
75%    4.514286e-01  4.622751e-01  1.458332e-02  2.037019e-02        1.0
max    9.231771e-01  9.634127e-01  2.122396e+00  2.200992e+00        1.0

In [13]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=1, shuffle=False)

In [15]:
import torch

#ae, _ = train_ae(dataset, feature_dim=5, latent_dim=16,
#             batch_size=32, epochs=80, lr=1e-3, device="cpu")

ae = MotionAutoencoderOld(
        feature_dim=5,
        latent_dim=16,
        dropout_prob=0.1
    ).to("cpu")

train_autoencoder(ae, train_loader, val_loader=val_loader, epochs=50, lr=0.01)

Epoch 001: 100%|██████████| 2082/2082 [00:11<00:00, 183.78it/s]

Epoch 001 — train: 0.019469 | val: 0.401140

Epoch 002: 100%|██████████| 2082/2082 [00:10<00:00, 192.93it/s]

Epoch 002 — train: 0.048083 | val: 0.960051

Epoch 003: 100%|██████████| 2082/2082 [00:10<00:00, 192.90it/s]

Epoch 003 — train: 0.048143 | val: 0.960808

Epoch 004: 100%|██████████| 2082/2082 [00:10<00:00, 198.29it/s]

Epoch 004 — train: 0.048131 | val: 0.966546

Epoch 005:  73%|███████▎  | 1516/2082 [00:08<00:03, 187.04it/s]

KeyboardInterrupt:

In [2]:
# save the trained autoencoder model
import torch
model_path = "results/models/motion_autoencoder2.0.pth"
torch.save(ae.state_dict(), model_path)
print(f"Model saved to {model_path}")

NameError: name 'ae' is not defined

# Other TCN autoencoder with modified dataset function

In [2]:
from src.embeddings.dataset import WindowDatasetTCN
from src.embeddings.train import train_tcn_ae

## First Check That the Dataset class works

In [3]:
processed_path = "data/processed"
paths = [os.path.join(processed_path, f) for f in os.listdir(processed_path) if f.endswith("30fps_processed.pkl")]

df_dict = {}
cols_to_keep = ['frame', 'hand_label', 'cx_smooth', 'cy_smooth']

with tqdm(total=len(paths), desc="Loading processed data") as pbar:
    for path in paths:
        vid = os.path.basename(path).replace("_30fps_processed.pkl", "")
        vid = vid.replace("hand_tracking_", "")
        df_dict[vid] = pd.read_pickle(path)[cols_to_keep]
        pbar.update(1)

Loading processed data: 100%|██████████| 86/86 [00:34<00:00,  2.51it/s]

In [4]:
dataset = WindowDatasetTCN(df_dict, hand="Right", feature_mode="pos_vel_acc", window_size=90, step_size=30, orig_fps=30.0, scaling=True)

Processing Right Hand Windows: 100%|██████████| 86/86 [00:00<00:00, 96.06it/s]

Computing scaling statistics from training data...

In [8]:
dataset[0][0]

tensor([[-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -0.0000e+00,  0.0000e+00, -0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [ 1.5087e+00, -4.6047e+00,  1.5087e+00, -4.6049e+00,  3.9479e-01,
          4.3950e+00,  1.0000e+00],
        [ 1.3498e+00, -1.7434e+00,  1.3498e+00, -1.7435e+00, -5.4350e-01,
          9.3230e+00,  1.0000e+00],
        [ 1.0930e+00, -4.0059e+00,  1.0930e+00, -4.0061e+00, -8.9448e-01,
         -7.4283e+00,  1.0000e+00],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [-0.0000e+00, -0.0000e+00, -0.0000e+00, -0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         -0.0000e+00,  0.0000e+00],
        [ 9.5894e+00,  8.1562e-01,  9.5894e+00,  8.1564e-01, -3.7293e+00,
         -7.2954e-01,  1.0000e+00],
        [ 8.5412e+00,  6.0208e-01,  8.5413e+00,  6.0210e-01, -3.7293e+00,
         -7.2955e-01,  1.0000e+00],
        [ 7.4931e+00,  3.8855e-01,  7.4931e+00,  3.8856e-01, -3.7293e+00,
         -7.2954e-01,  1.0000e+00],
        [ 7.8103e+00, -2.7901e-02,  7.8104e+00, -2.7902e-02,  1.1620e+00,
         -1.3929e+00,  1.0000e+00],
        [ 5.5800e+00, -3.9045e-01,  5.5800e+00, -3.9046e-01, -7.9641e+00,
         -1.2167e+00,  1.0000e+00],
        [ 2.9946e+00,  9.8412e-02,  2.9946e+00,  9.8415e-02, -9.2362e+00,
          1.5668e+00,  1.0000e+00],
        [ 1.6932e+00,  4.6389e-01,  1.6932e+00,  4.6390e-01, -4.6362e+00,
          1.1634e+00,  1.0000e+00],
        [ 1.5750e+00,  9.0601e-01,  1.5750e+00,  9.0604e-01, -3.9810e-01,
          1.4140e+00,  1.0000e+00],
        [ 1.0688e+00,  1.4517e+00,  1.0688e+00,  1.4518e+00, -1.7880e+00,
          1.7527e+00,  1.0000e+00],
        [ 7.1579e-01,  1.6930e+00,  7.1580e-01,  1.6931e+00, -1.2389e+00,
          7.5738e-01,  1.0000e+00],
        [ 8.5755e-01,  1.8315e+00,  8.5756e-01,  1.8315e+00,  5.3329e-01,
          4.2121e-01,  1.0000e+00],
        [ 6.3978e-01,  1.5380e+00,  6.3978e-01,  1.5380e+00, -7.5464e-01,
         -9.9090e-01,  1.0000e+00],
        [ 7.8864e-01,  1.1004e+00,  7.8864e-01,  1.1004e+00,  5.5872e-01,
         -1.4620e+00,  1.0000e+00],
        [ 1.0556e+00,  6.2985e-01,  1.0556e+00,  6.2987e-01,  9.8171e-01,
         -1.5698e+00,  1.0000e+00],
        [ 1.0558e+00,  2.0385e-01,  1.0558e+00,  2.0386e-01,  2.6188e-02,
         -1.4242e+00,  1.0000e+00],
        [ 1.0845e+00, -5.8496e-02,  1.0845e+00, -5.8498e-02,  1.2820e-01,
         -8.8914e-01,  1.0000e+00],
        [ 9.7271e-01, -1.4059e-01,  9.7272e-01, -1.4059e-01, -3.7481e-01,
         -2.9981e-01,  1.0000e+00],
        [ 6.8844e-01, -2.6426e-01,  6.8844e-01, -2.6427e-01, -9.9286e-01,
         -4.3576e-01,  1.0000e+00],
        [ 5.5602e-01, -1.4299e-01,  5.5602e-01, -1.4299e-01, -4.4889e-01,
          3.6503e-01,  1.0000e+00],
        [ 3.1643e-01, -1.2311e-01,  3.1643e-01, -1.2312e-01, -8.3278e-01,
          3.3556e-02,  1.0000e+00],
        [ 1.9521e-01, -8.5280e-02,  1.9521e-01, -8.5283e-02, -4.0878e-01,
          9.2249e-02,  1.0000e+00],
        [ 3.8929e-02, -1.1937e-01,  3.8929e-02, -1.1938e-01, -5.3434e-01,
         -1.4289e-01,  1.0000e+00],
        [-3.5921e-01, -1.7374e-02, -3.5921e-01, -1.7375e-02, -1.4007e+00,
          3.0203e-01,  1.0000e+00],
        [-5.3205e-01,  6.5519e-02, -5.3205e-01,  6.5521e-02, -5.9368e-01,
          2.3957e-01,  1.0000e+00],
        [-6.4764e-01,  6.6692e-03, -6.4765e-01,  6.6693e-03, -3.8862e-01,
         -2.2383e-01,  1.0000e+00],
        [-7.8992e-01, -1.9594e-01, -7.8993e-01, -1.9595e-01, -4.8420e-01,
         -6.9382e-01,  1.0000e+00],
        [-6.6622e-01, -2.2810e-01, -6.6623e-01, -2.2811e-01,  4.6860e-01,
         -1.3660e-01,  1.0000e+00],
        [-6.5706e-01, -4.1272e-01, -6.5707e-01, -4.1274e-01,  5.8276e-02,
         -6.3502e-01,  1.0000e+00],
        [-5.5878e-01, -4.7504e-01, -5.5878e-01, -4.7506e-01,  3.7756e-01,
         -2.3517e-01,  1.0000e+00],
        [-5.6654e-01, -4.6926e-01, -5.6654e-01, -4.6928e-01, -2.3273e-03,
         -1.2545e-02,  1.0000e+00],
        [-5.4316e-01, -2.6639e-01, -5.4317e-01, -2.6640e-01,  1.0920e-01,
          6.3183e-01,  1.0000e+00],
        [-5.0325e-01,  7.6439e-03, -5.0326e-01,  7.6441e-03,  1.6844e-01,
          8.6448e-01,  1.0000e+00],
        [-4.1619e-01,  2.3367e-01, -4.1619e-01,  2.3368e-01,  3.3736e-01,
          7.0752e-01,  1.0000e+00],
        [-3.5915e-01,  4.8347e-01, -3.5916e-01,  4.8349e-01,  2.2979e-01,
          7.8525e-01,  1.0000e+00],
        [-1.5906e-01,  8.4064e-01, -1.5906e-01,  8.4067e-01,  7.4225e-01,
          1.1363e+00,  1.0000e+00],
        [-1.4047e-01,  8.9883e-01, -1.4048e-01,  8.9886e-01,  9.2053e-02,
          1.5880e-01,  1.0000e+00],
        [-1.5945e-01,  8.9647e-01, -1.5945e-01,  8.9650e-01, -4.2502e-02,
         -3.9140e-02,  1.0000e+00],
        [-1.9413e-01,  5.9222e-01, -1.9413e-01,  5.9224e-01, -9.8753e-02,
         -1.0261e+00,  1.0000e+00],
        [-2.4402e-01,  3.1094e-01, -2.4402e-01,  3.1095e-01, -1.5325e-01,
         -9.5104e-01,  1.0000e+00],
        [-2.0768e-01,  4.8098e-02, -2.0769e-01,  4.8100e-02,  1.5564e-01,
         -8.9074e-01,  1.0000e+00],
        [-4.7672e-02, -1.8865e-01, -4.7673e-02, -1.8866e-01,  5.9867e-01,
         -8.0546e-01,  1.0000e+00],
        [ 2.4172e-01, -2.8342e-01,  2.4172e-01, -2.8343e-01,  1.0622e+00,
         -3.4126e-01,  1.0000e+00],
        [ 6.5372e-01, -4.5231e-01,  6.5373e-01, -4.5233e-01,  1.5014e+00,
         -5.8358e-01,  1.0000e+00],
        [ 9.3508e-01, -7.4854e-01,  9.3508e-01, -7.4856e-01,  1.0334e+00,
         -9.9990e-01,  1.0000e+00],
        [ 1.1746e+00, -8.8434e-01,  1.1746e+00, -8.8437e-01,  8.8353e-01,
         -4.7541e-01,  1.0000e+00],
        [ 1.1784e+00, -8.4992e-01,  1.1784e+00, -8.4995e-01,  3.8984e-02,
          8.1086e-02,  1.0000e+00],
        [ 1.0616e+00, -5.9605e-01,  1.0616e+00, -5.9607e-01, -3.9271e-01,
          7.9856e-01,  1.0000e+00],
        [ 8.7668e-01, -4.1630e-01,  8.7669e-01, -4.1631e-01, -6.3710e-01,
          5.5623e-01,  1.0000e+00],
        [ 6.6673e-01, -2.0928e-01,  6.6674e-01, -2.0928e-01, -7.2661e-01,
          6.4538e-01,  1.0000e+00],
        [ 5.6372e-01, -7.9391e-02,  5.6373e-01, -7.9393e-02, -3.4354e-01,
          3.9321e-01,  1.0000e+00],
        [ 4.7049e-01, -7.8900e-02,  4.7049e-01, -7.8903e-02, -3.0853e-01,
         -2.9831e-02,  1.0000e+00],
        [ 3.2420e-01, -2.2720e-01,  3.2420e-01, -2.2721e-01, -4.9855e-01,
         -5.1628e-01,  1.0000e+00],
        [ 2.7140e-01, -3.0845e-01,  2.7140e-01, -3.0846e-01, -1.6368e-01,
         -2.9705e-01,  1.0000e+00],
        [ 2.0530e-01, -1.6752e-01,  2.0530e-01, -1.6753e-01, -2.1132e-01,
          4.2929e-01,  1.0000e+00],
        [ 2.9022e-01, -3.3679e-02,  2.9022e-01, -3.3680e-02,  3.2969e-01,
          4.0615e-01,  1.0000e+00],
        [ 3.3539e-01,  1.4222e-01,  3.3539e-01,  1.4222e-01,  1.8728e-01,
          5.4362e-01,  1.0000e+00],
        [ 3.9558e-01,  2.9285e-01,  3.9558e-01,  2.9286e-01,  2.4109e-01,
          4.6104e-01,  1.0000e+00],
        [ 3.5244e-01,  2.6609e-01,  3.5244e-01,  2.6610e-01, -1.2905e-01,
         -1.1892e-01,  1.0000e+00],
        [ 7.6545e-02,  3.6640e-01,  7.6545e-02,  3.6641e-01, -9.6285e-01,
          2.9651e-01,  1.0000e+00],
        [-1.6408e-01,  4.6602e-01, -1.6409e-01,  4.6604e-01, -8.3651e-01,
          2.9427e-01,  1.0000e+00],
        [-3.2628e-01,  5.4040e-01, -3.2628e-01,  5.4041e-01, -5.5555e-01,
          2.1172e-01,  1.0000e+00],
        [-4.2109e-01,  6.1176e-01, -4.2109e-01,  6.1178e-01, -3.1414e-01,
          2.0187e-01,  1.0000e+00],
        [-2.7157e-01,  7.1170e-01, -2.7158e-01,  7.1172e-01,  5.6106e-01,
          2.9531e-01,  1.0000e+00],
        [-2.3524e-01,  7.1895e-01, -2.3524e-01,  7.1898e-01,  1.5564e-01,
         -7.7170e-03,  1.0000e+00],
        [-1.2857e-02,  5.9848e-01, -1.2858e-02,  5.9850e-01,  8.2208e-01,
         -4.2529e-01,  1.0000e+00],
        [ 2.2236e-01,  3.9656e-01,  2.2236e-01,  3.9657e-01,  8.6807e-01,
         -6.9158e-01,  1.0000e+00],
        [ 3.7990e-01,  3.3594e-01,  3.7990e-01,  3.3595e-01,  5.8980e-01,
         -2.2963e-01,  1.0000e+00],
        [ 5.7570e-01,  3.6697e-01,  5.7570e-01,  3.6698e-01,  7.2689e-01,
          7.0019e-02,  1.0000e+00],
        [ 7.5151e-01,  4.4322e-01,  7.5152e-01,  4.4324e-01,  6.5528e-01,
          2.1786e-01,  1.0000e+00],
        [ 7.4892e-01,  6.1227e-01,  7.4892e-01,  6.1229e-01,  1.6185e-02,
          5.2122e-01,  1.0000e+00],
        [ 8.2180e-01,  8.0392e-01,  8.2180e-01,  8.0395e-01,  2.8653e-01,
          5.9515e-01,  1.0000e+00],
        [ 4.8380e-01,  8.1452e-01,  4.8381e-01,  8.1455e-01, -1.1853e+00,
          3.2143e-03,  1.0000e+00],
        [ 3.2253e-01,  7.4934e-01,  3.2253e-01,  7.4937e-01, -5.5224e-01,
         -2.4452e-01,  1.0000e+00],
        [ 2.0997e-01,  5.4122e-01,  2.0997e-01,  5.4124e-01, -3.7774e-01,
         -7.1184e-01,  1.0000e+00],
        [-2.1253e-02,  3.3765e-01, -2.1254e-02,  3.3766e-01, -8.0284e-01,
         -6.9697e-01,  1.0000e+00],
        [ 1.5994e-01,  7.5426e-02,  1.5994e-01,  7.5428e-02,  6.7454e-01,
         -8.8874e-01,  1.0000e+00],
        [ 9.8069e-02, -2.7197e-01,  9.8069e-02, -2.7198e-01, -1.9615e-01,
         -1.1672e+00,  1.0000e+00],
        [ 2.3535e-01, -2.7164e-01,  2.3535e-01, -2.7165e-01,  5.1725e-01,
         -3.0352e-02,  1.0000e+00],
        [ 4.4272e-01, -2.0570e-01,  4.4273e-01, -2.0571e-01,  7.6833e-01,
          1.8412e-01,  1.0000e+00],
        [ 4.0407e-01, -6.2850e-02,  4.0407e-01, -6.2852e-02, -1.1301e-01,
          4.3560e-01,  1.0000e+00]])

In [6]:
ae, _ = train_tcn_ae(dataset, feature_dim=7, latent_dim=16,
             batch_size=32, epochs=20, lr=1e-3, device="cpu")

Epoch 001: 100%|██████████| 1100/1100 [01:25<00:00, 12.88it/s]

Epoch 001 — loss: 0.601497

Epoch 002: 100%|██████████| 1100/1100 [01:31<00:00, 12.00it/s]

Epoch 002 — loss: 0.537886

Epoch 003: 100%|██████████| 1100/1100 [01:35<00:00, 11.52it/s]

Epoch 003 — loss: 0.505215

Epoch 004: 100%|██████████| 1100/1100 [01:33<00:00, 11.76it/s]

Epoch 004 — loss: 0.485177

Epoch 005: 100%|██████████| 1100/1100 [01:36<00:00, 11.35it/s]

Epoch 005 — loss: 0.465587

Epoch 006: 100%|██████████| 1100/1100 [01:34<00:00, 11.62it/s]

Epoch 006 — loss: 0.453339

Epoch 007: 100%|██████████| 1100/1100 [01:52<00:00,  9.81it/s]

Epoch 007 — loss: 0.441266

Epoch 008: 100%|██████████| 1100/1100 [01:33<00:00, 11.75it/s]

Epoch 008 — loss: 0.432681

Epoch 009: 100%|██████████| 1100/1100 [01:32<00:00, 11.86it/s]

Epoch 009 — loss: 0.424354

Epoch 010: 100%|██████████| 1100/1100 [01:28<00:00, 12.37it/s]

Epoch 010 — loss: 0.417941

Epoch 011: 100%|██████████| 1100/1100 [01:28<00:00, 12.44it/s]

Epoch 011 — loss: 0.410934

Epoch 012: 100%|██████████| 1100/1100 [01:31<00:00, 12.07it/s]

Epoch 012 — loss: 0.407395

Epoch 013:   2%|▏         | 20/1100 [00:01<01:31, 11.82it/s]

KeyboardInterrupt: